---
- name: Get VMs Artifact
  hosts: all 
  gather_facts: no
  tasks:
   - name: Get Minimum Artifact
     setup:
      gather_subset:
        - min
        - hardware
        - all_ipv4_addresses

   - name: Show total memory 
     debug:
      msg: "[INFO] - {{ inventory_hostname }} has {{ ansible_memtotal_mb // 1024 }} GB"

   - name: Show warning if memory is less than 16GB
     debug:
      msg: "[WARNING] - {{ inventory_hostname }} has less than 16GB RAM"
     when: ansible_memtotal_mb < 16384

   - name: Show all ipv4 address
     debug: var=ansible_default_ipv4
